DEFAULT_CAMERA_CONFIG = {
    "distance": 4.0,
}

DEFAULT_FORWARD_REWARD_WEIGHT = 1.0
DEFAULT_CTRL_COST_WEIGHT = 0.5
DEFAULT_CONTACT_COST_WEIGHT = 5e-4
DEFAULT_HEALTHY_REWARD = 1.0

DEFAULT_HEALTHY_Z_RANGE = (0.2, 1.0)
DEFAULT_CONTACT_FORCE_RANGE = (-1.0, 1.0)

DEFAULT_RESET_NOISE_SCALE = 0.1
DEFAULT_FRAME_SKIP = 5
