import numpy as np

DEFAULT_CAMERA_CONFIG = {
    "trackbodyid": 1,
    "distance": 4.0,
    "lookat": np.array((0.0, 0.0, 2.0)),
    "elevation": -20.0,
}

DEFAULT_FRAME_SKIP = 5

DEFAULT_FORWARD_REWARD_WEIGHT = 1.25
DEFAULT_CTRL_COST_WEIGHT = 0.1
DEFAULT_CONTACT_COST_WEIGHT = 5e-7
DEFAULT_CONTACT_COST_RANGE = (-np.inf, 10.0)

DEFAULT_HEALTHY_REWARD = 5.0
DEFAULT_HEALTHY_Z_RANGE = (1.0, 2.0)
DEFAULT_TERMINATE_WHEN_UNHEALTHY = True

DEFAULT_RESET_NOISE_SCALE = 1e-2
